[GLOBAL]
pants_version = "2.14.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.typecheck.mypy",
]
[python]
  interpreter_constraints = ["CPython==3.10.*"]
[source]
  root_patterns = ["/"]
[anonymous-telemetry]
  enabled = false
